- hosts: all

  vars:
    kubernetes_allow_pods_on_master: true
    # K8s version if Debian is used
    kubernetes_version: '1.18'
    # K8s version if CentOS is used
    kubernetes_version_rhel_package: '1.18.0'
    kubernetes_enable_web_ui: false
    kubernetes_web_ui_manifest_file: https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-rc7/aio/deploy/recommended.yaml
    
    kubernetes_pod_network:
      # Flannel CNI.
      cni: 'flannel'
      cidr: '10.244.0.0/16'    

  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes
