- hosts: all

  vars:
    kubernetes_allow_pods_on_master: true
    kubernetes_version_rhel_package: '1.18.0'
    kubernetes_pod_network:
      # Flannel CNI.
      cni: 'flannel'
      cidr: '10.244.0.0/16'    

  roles:
    - geerlingguy.docker
    - geerlingguy.kubernetes
